export const FETCH_MOVIES_START = "FETCH_MOVIES_START";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";

export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_START = "FETCH_MOVIE_START";
export const FETCH_MOVIE_ERROR = "FETCH_MOVIE_ERROR";

export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_START = "DELETE_MOVIE_START";
export const DELETE_MOVIE_ERROR = "DELETE_MOVIE_ERROR";

export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_START = "CREATE_MOVIE_START";
export const CREATE_MOVIE_ERROR = "CREATE_MOVIE_ERROR";

export const EDIT_MOVIE_SUCCESS = "EDIT_MOVIE_SUCCESS";
export const EDIT_MOVIE_START = "EDIT_MOVIE_START";
export const EDIT_MOVIE_ERROR = "EDIT_MOVIE_ERROR";

export const UPDATE_FILTER_SUCCESS = "UPDATE_FILTER_SUCCESS";
export const UPDATE_FILTER_START = "UPDATE_FILTER_START";
export const UPDATE_FILTER_ERROR = "UPDATE_FILTER_ERROR";

export const UPDATE_SORTING_SUCCESS = "UPDATE_SORTING_SUCCESS";
export const UPDATE_SORTING_START = "UPDATE_SORTING_START";
export const UPDATE_SORTING_ERROR = "UPDATE_SORTING_ERROR";
